name: dou_um_help_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0 
  cloud_firestore: ^4.13.0 
  provider: ^6.1.0 
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mask_text_input_formatter: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png